#!/bin/bash

OP_SYS="ubuntu"
# Check OS type and install dialog package
. /etc/lsb-release
OS=$DISTRIB_ID
if [ "$OS" == "Ubuntu" ]; then
  if ! dpkg-query -W -f'${Status}' "dialog" 2>/dev/null | grep -q "ok installed"; then
    sudo apt-get install -y dialog
  fi
else
  OP_SYS="centos"
  if ! rpm -qa | grep -qw dialog; then
    sudo yum install -y dialog
  fi
fi

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

add_user() {
  exec 3>&1;
  username=$(dialog --inputbox "Please enter a username" 0 0 2>&1 1>&3);
  if [ "$username" != "" ] ; then
    password=$(dialog --passwordbox "Please enter a password" 0 0 2>&1 1>&3);
  fi
  exec 3>&-;
  if [ "$username" != "" ] && [ "$password" != "" ] ; then
    printf "$username\n$password" | sh /usr/local/bin/ACG-Package-Suite/$OP_SYS/add_a_user.sh
  fi
}

install_software() {
  COUNTER=1
  RADIOLIST=()
  SCRIPTLIST=()
  for i in /usr/local/bin/ACG-Package-Suite/$OP_SYS/*; do
    if [[ $i == *.sh ]] ; then
      line="$(sed -n '2p' $i)"
      OPTION="${line//#}"
      SCRIPTLIST+=($i)
      RADIOLIST+=($COUNTER "${OPTION}" off)
      let COUNTER=COUNTER+1
    fi
  done
  exec 3>&1;
  toInstall=$(dialog --checklist "Choose software:" 10 60 $COUNTER "${RADIOLIST[@]}" 2>&1 1>&3);
  exec 3>&-;
  for prog in $toInstall; do
    sh ${SCRIPTLIST[$prog-1]}
  done
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "UMaine ACG System Configurator" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Add a user" \
    "2" "Install new software" \
    "3" "Update ACG Suite" \
    "4" "Reboot system" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      add_user;;
    2 )
      install_software;;
    3 )
      sh /usr/local/bin/ACG-Package-Suite/update_suite.sh;;
    4 )
      clear
      sudo reboot -i
      exit;;
  esac
done
