#!/bin/bash

if ! dpkg-query -W -f'${Status}' "dialog" 2>/dev/null | grep -q "ok installed"; then
  sudo apt-get install -y dialog
fi

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

add_user() {
  exec 3>&1;
  username=$(dialog --inputbox "Please enter a username" 0 0 2>&1 1>&3);
  password=$(dialog --passwordbox "Please enter a password" 0 0 2>&1 1>&3);
  exec 3>&-;
  printf "$username\n$password" | sh /usr/local/bin/ACG-Package-Suite/add_a_user.sh
}

install_software() {
  exec 3>&1;
  toInstall=$(dialog --checklist "Choose software:" 10 60 4 \
              "1" "Window Manager (xfce)" off \
              "2" "Remote Desktop (Chrome Remote Desktop)" off \
              "3" "Office Suite (Libreoffice)" off \
              "4" "USB IP (Connect USB devices to server)" off \
              "5" "Archivematica Server" off \
              "6" "AtoM Server" off \
              2>&1 1>&3);
  exec 3>&-;
  for prog in $toInstall; do
    case $prog in
      1)
        sh /usr/local/bin/ACG-Package-Suite/install_xfce4_desktop.sh;;
      2)
        sh /usr/local/bin/ACG-Package-Suite/install_chrome_and_remote_desktop.sh;;
      3)
        sh /usr/local/bin/ACG-Package-Suite/install_office_suite.sh;;
      4)
        sh /usr/local/bin/ACG-Package-Suite/install_usbip.sh;;
      5)
        sh /usr/local/bin/ACG-Package-Suite/install_archivematica.sh;;
      6)
        sh /usr/local/bin/ACG-Package-Suite/install_atom.sh;;
    esac
  done
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "UMaine ACG System Configurator" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 4 \
    "1" "Add a user" \
    "2" "Install new software" \
    "3" "Update ACG Suite" \
    "4" "Reboot system" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      add_user;;
    2 )
      install_software;;
    3 )
      sh /usr/local/bin/ACG-Package-Suite/update_suite.sh;;
    4 )
      clear
      sudo reboot -i
      exit;;
  esac
done
