#!/bin/bash
#Desktop Environment
###################################################################
# 
# Install ubuntu 1804 desktop
#
###################################################################

echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen
sudo timedatectl set-timezone America/New_York
sudo apt-get -y  update
sudo apt-get -y  upgrade 
sudo apt  -y autoremove

sudo apt-get  -y install
sudo apt-get install -y  -f ubuntu-desktop

sudo apt-get -f -y install

echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen
sudo timedatectl set-timezone America/New_York
echo PATH=\"$PATH\"| sudo tee /etc/environment

/usr/local/bin/ACG-Package-Suite/ubuntu/install_chrome_and_remote_desktop.sh


