#!/bin/bash
#Desktop Environment
###################################################################
# 
# Install ubuntu desktop
#
###################################################################
sudo apt-get install python3-pip
sudo pip3 install apt-mirror-updater
apt-mirror-updater -a

echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen
sudo timedatectl set-timezone America/New_York
sudo apt-get -y  update
sudo apt-get -y  upgrade 
sudo apt  -y autoremove
sudo apt-get -y install linux-generic
sudo apt-get update
sudo apt -y autoremove

sudo apt-get  -y install
sudo apt-get install -y  -f ubuntu-desktop

sudo apt-get -f -y install

echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen
sudo timedatectl set-timezone America/New_York
echo PATH=\"$PATH\"| sudo tee /etc/environment

/usr/local/bin/ACG-Package-Suite/ubuntu/install_chrome_and_remote_desktop.sh
/usr/local/bin/ACG-Package-Suite/ubuntu/fix_online_accounts_2004.sh

sudo apt-get install -y firefox
